# Generated by Django 4.2 on 2024-01-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='no_of_likes',
        ),
    ]
